# Generated by Django 2.0.6 on 2018-07-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('uploader', models.CharField(max_length=25)),
                ('up_votes', models.IntegerField(default=0)),
                ('video_file', models.FileField(upload_to='uploads/videos/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
