# Generated by Django 2.0.7 on 2018-07-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20180718_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='stream_key',
            field=models.CharField(default='stream', max_length=50),
            preserve_default=False,
        ),
    ]
