# Generated by Django 2.0.6 on 2018-07-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_up_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(default='uploads/videos/thumbnails/t.png', upload_to='uploads/videos/thumbnails/'),
            preserve_default=False,
        ),
    ]
