# Generated by Django 2.0.6 on 2018-07-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='listed',
            field=models.BooleanField(default=True),
        ),
    ]
