# Generated by Django 2.0.7 on 2018-07-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_podcast_podcastcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='uploader',
        ),
        migrations.AddField(
            model_name='playlist',
            name='podcasts',
            field=models.ManyToManyField(to='videos.Podcast'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='streams',
            field=models.ManyToManyField(to='videos.LiveStream'),
        ),
    ]
