# Generated by Django 2.0.7 on 2018-07-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20180722_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='podcasts',
            field=models.ManyToManyField(blank=True, to='videos.Podcast'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='streams',
            field=models.ManyToManyField(blank=True, to='videos.LiveStream'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(blank=True, to='videos.Video'),
        ),
    ]
