# Generated by Django 2.0.7 on 2018-07-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20180722_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='subscription_manager',
            field=models.ManyToManyField(blank=True, to='videos.SubscriptionManager'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='subscription_manager',
            field=models.ManyToManyField(blank=True, to='videos.SubscriptionManager'),
        ),
        migrations.AlterField(
            model_name='video',
            name='subscription_manager',
            field=models.ManyToManyField(blank=True, to='videos.SubscriptionManager'),
        ),
    ]
