# Generated by Django 2.0.7 on 2018-07-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmanager',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
