# Generated by Django 2.0.7 on 2018-07-27 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0010_blog_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptionmanager',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='subscriptionmanager',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.SubscriptionManager'),
        ),
    ]
