# Generated by Django 2.0.7 on 2018-08-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_auto_20180727_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='listed',
            field=models.BooleanField(default=True),
        ),
    ]
